version: "3.8"


services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python app.py run -h 0.0.0.0
        ports:
            - 5000:5000
        container_name: app