version: "3.8"


services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python app.py run -h 0.0.0.0
        environment:
            STAGE: test
            SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
        ports:
            - 5000:5000
        volumes: 
            - '.:/usr/src/app'
        depends_on: 
            - db
        container_name: app
    db:
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
        image: postgres:latest
        networks:
            - default
        ports:
            - 5405:5432
        restart: always
        container_name: databse
        volumes:
            - './postgres-data:/var/lib/postgresql/data'